_base_: ['../_base_/default_runtime.yaml']

task:
  type: ObjectDetectionTask

model:
  type: UltralyticsDetAdapter
  yaml_model: yolov8n.yaml

runner:
  type: EpochBasedRunner
  max_epochs: 50

optimizer:
  type: AdamW
  lr: 0.001
  weight_decay: 0.0001
  
val_evaluator:
  metrics: []
  plotters: []
